services:
  mysql:
    image: mysql:8.0
    container_name: mysql-database-tasko
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tasko_database
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newuser
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: